/* eslint-disable quotes */
export const realms = [
  { name: 'Aegwynn', value: 'aegwynn' },
  { name: 'Aerie Peak', value: 'aerie-peak' },
  { name: 'Agamaggan', value: 'agamaggan' },
  { name: 'Aggramar', value: 'aggramar' },
  { name: 'Akama', value: 'akama' },
  { name: 'Alexstrasza', value: 'alexstrasza' },
  { name: 'Alleria', value: 'alleria' },
  { name: 'Altar of Storms', value: 'altar-of-storms' },
  { name: 'Alterac Mountains', value: 'alterac-mountains' },
  { name: "Aman'Thul", value: 'aman-thul' },
  { name: 'Andorhal', value: 'andorhal' },
  { name: 'Anetheron', value: 'anetheron' },
  { name: 'Antonidas', value: 'antonidas' },
  { name: "Anub'arak", value: 'anub-arak' },
  { name: 'Anvilmar', value: 'anvilmar' },
  { name: 'Arathor', value: 'arathor' },
  { name: 'Archimonde', value: 'archimonde' },
  { name: 'Area 52', value: 'area-52' },
  { name: 'Argent Dawn', value: 'argent-dawn' },
  { name: 'Arthas', value: 'arthas' },
  { name: 'Arygos', value: 'arygos' },
  { name: 'Auchindoun', value: 'auchindoun' },
  { name: 'Azgalor', value: 'azgalor' },
  { name: 'Azjol-Nerub', value: 'azjol-nerub' },
  { name: 'Azralon', value: 'azralon' },
  { name: 'Azshara', value: 'azshara' },
  { name: 'Azuremyst', value: 'azuremyst' },
  { name: 'Baelgun', value: 'baelgun' },
  { name: 'Balnazzar', value: 'balnazzar' },
  { name: 'Barthilas', value: 'barthilas' },
  { name: 'Black Dragonflight', value: 'black-dragonflight' },
  { name: 'Blackhand', value: 'blackhand' },
  { name: 'Blackrock', value: 'blackrock' },
  { name: 'Blackwater Raiders', value: 'blackwater-raiders' },
  { name: 'Blackwing Lair', value: 'blackwing-lair' },
  { name: "Blade's Edge", value: 'blade-s-edge' },
  { name: 'Bladefist', value: 'bladefist' },
  { name: 'Bleeding Hollow', value: 'bleeding-hollow' },
  { name: 'Blood Furnace', value: 'blood-furnace' },
  { name: 'Bloodhoof', value: 'bloodhoof' },
  { name: 'Bloodscalp', value: 'bloodscalp' },
  { name: 'Bonechewer', value: 'bonechewer' },
  { name: 'Borean Tundra', value: 'borean-tundra' },
  { name: 'Boulderfist', value: 'boulderfist' },
  { name: 'Bronzebeard', value: 'bronzebeard' },
  { name: 'Burning Blade', value: 'burning-blade' },
  { name: 'Burning Legion', value: 'burning-legion' },
  { name: 'Caelestrasz', value: 'caelestrasz' },
  { name: 'Cairne', value: 'cairne' },
  { name: 'Cenarion Circle', value: 'cenarion-circle' },
  { name: 'Cenarius', value: 'cenarius' },
  { name: "Cho'gall", value: 'cho-gall' },
  { name: 'Chromaggus', value: 'chromaggus' },
  { name: 'Coilfang', value: 'coilfang' },
  { name: 'Crushridge', value: 'crushridge' },
  { name: 'Daggerspine', value: 'daggerspine' },
  { name: 'Dalaran', value: 'dalaran' },
  { name: 'Dalvengyr', value: 'dalvengyr' },
  { name: 'Dark Iron', value: 'dark-iron' },
  { name: 'Darkspear', value: 'darkspear' },
  { name: 'Darrowmere', value: 'darrowmere' },
  { name: "Dath'Remar", value: 'dath-remar' },
  { name: 'Dawnbringer', value: 'dawnbringer' },
  { name: 'Deathwing', value: 'deathwing' },
  { name: 'Demon Soul', value: 'demon-soul' },
  { name: 'Dentarg', value: 'dentarg' },
  { name: 'Destromath', value: 'destromath' },
  { name: 'Dethecus', value: 'dethecus' },
  { name: 'Detheroc', value: 'detheroc' },
  { name: 'Doomhammer', value: 'doomhammer' },
  { name: 'Draenor', value: 'draenor' },
  { name: 'Dragonblight', value: 'dragonblight' },
  { name: 'Dragonmaw', value: 'dragonmaw' },
  { name: "Drak'Tharon", value: 'drak-tharon' },
  { name: "Drak'thul", value: 'drak-thul' },
  { name: 'Draka', value: 'draka' },
  { name: 'Drakkari', value: 'drakkari' },
  { name: 'Dreadmaul', value: 'dreadmaul' },
  { name: 'Drenden', value: 'drenden' },
  { name: 'Dunemaul', value: 'dunemaul' },
  { name: 'Durotan', value: 'durotan' },
  { name: 'Duskwood', value: 'duskwood' },
  { name: 'Earthen Ring', value: 'earthen-ring' },
  { name: 'Echo Isles', value: 'echo-isles' },
  { name: 'Eitrigg', value: 'eitrigg' },
  { name: "Eldre'Thalas", value: 'eldre-thalas' },
  { name: 'Elune', value: 'elune' },
  { name: 'Emerald Dream', value: 'emerald-dream' },
  { name: 'Eonar', value: 'eonar' },
  { name: 'Eredar', value: 'eredar' },
  { name: 'Executus', value: 'executus' },
  { name: 'Exodar', value: 'exodar' },
  { name: 'Farstriders', value: 'farstriders' },
  { name: 'Feathermoon', value: 'feathermoon' },
  { name: 'Fenris', value: 'fenris' },
  { name: 'Firetree', value: 'firetree' },
  { name: 'Fizzcrank', value: 'fizzcrank' },
  { name: 'Frostmane', value: 'frostmane' },
  { name: 'Frostmourne', value: 'frostmourne' },
  { name: 'Frostwolf', value: 'frostwolf' },
  { name: 'Galakrond', value: 'galakrond' },
  { name: 'Gallywix', value: 'gallywix' },
  { name: 'Garithos', value: 'garithos' },
  { name: 'Garona', value: 'garona' },
  { name: 'Garrosh', value: 'garrosh' },
  { name: 'Ghostlands', value: 'ghostlands' },
  { name: 'Gilneas', value: 'gilneas' },
  { name: 'Gnomeregan', value: 'gnomeregan' },
  { name: 'Goldrinn', value: 'goldrinn' },
  { name: 'Gorefiend', value: 'gorefiend' },
  { name: 'Gorgonnash', value: 'gorgonnash' },
  { name: 'Greymane', value: 'greymane' },
  { name: 'Grizzly Hills', value: 'grizzly-hills' },
  { name: "Gul'dan", value: 'gul-dan' },
  { name: 'Gundrak', value: 'gundrak' },
  { name: 'Gurubashi', value: 'gurubashi' },
  { name: 'Hakkar', value: 'hakkar' },
  { name: 'Haomarush', value: 'haomarush' },
  { name: 'Hellscream', value: 'hellscream' },
  { name: 'Hydraxis', value: 'hydraxis' },
  { name: 'Hyjal', value: 'hyjal' },
  { name: 'Icecrown', value: 'icecrown' },
  { name: 'Illidan', value: 'illidan' },
  { name: 'Jaedenar', value: 'jaedenar' },
  { name: "Jubei'Thos", value: 'jubei-thos' },
  { name: "Kael'thas", value: 'kael-thas' },
  { name: 'Kalecgos', value: 'kalecgos' },
  { name: 'Kargath', value: 'kargath' },
  { name: "Kel'Thuzad", value: 'kel-thuzad' },
  { name: 'Khadgar', value: 'khadgar' },
  { name: 'Khaz Modan', value: 'khaz-modan' },
  { name: "Khaz'goroth", value: 'khaz-goroth' },
  { name: "Kil'jaeden", value: 'kil-jaeden' },
  { name: 'Kilrogg', value: 'kilrogg' },
  { name: 'Kirin Tor', value: 'kirin-tor' },
  { name: 'Korgath', value: 'korgath' },
  { name: 'Korialstrasz', value: 'korialstrasz' },
  { name: 'Kul Tiras', value: 'kul-tiras' },
  { name: 'Laughing Skull', value: 'laughing-skull' },
  { name: 'Lethon', value: 'lethon' },
  { name: 'Lightbringer', value: 'lightbringer' },
  { name: "Lightning's Blade", value: 'lightning-s-blade' },
  { name: 'Lightninghoof', value: 'lightninghoof' },
  { name: 'Llane', value: 'llane' },
  { name: 'Lothar', value: 'lothar' },
  { name: 'Madoran', value: 'madoran' },
  { name: 'Maelstrom', value: 'maelstrom' },
  { name: 'Magtheridon', value: 'magtheridon' },
  { name: 'Maiev', value: 'maiev' },
  { name: "Mal'Ganis", value: 'mal-ganis' },
  { name: 'Malfurion', value: 'malfurion' },
  { name: 'Malorne', value: 'malorne' },
  { name: 'Malygos', value: 'malygos' },
  { name: 'Mannoroth', value: 'mannoroth' },
  { name: 'Medivh', value: 'medivh' },
  { name: 'Misha', value: 'misha' },
  { name: "Mok'Nathal", value: 'mok-nathal' },
  { name: 'Moon Guard', value: 'moon-guard' },
  { name: 'Moonrunner', value: 'moonrunner' },
  { name: "Mug'thol", value: 'mug-thol' },
  { name: 'Muradin', value: 'muradin' },
  { name: 'Nagrand', value: 'nagrand' },
  { name: 'Nathrezim', value: 'nathrezim' },
  { name: 'Nazgrel', value: 'nazgrel' },
  { name: 'Nazjatar', value: 'nazjatar' },
  { name: 'Nemesis', value: 'nemesis' },
  { name: "Ner'zhul", value: 'ner-zhul' },
  { name: 'Nesingwary', value: 'nesingwary' },
  { name: 'Nordrassil', value: 'nordrassil' },
  { name: 'Norgannon', value: 'norgannon' },
  { name: 'Onyxia', value: 'onyxia' },
  { name: 'Perenolde', value: 'perenolde' },
  { name: 'Proudmoore', value: 'proudmoore' },
  { name: "Quel'Thalas", value: 'quel-thalas' },
  { name: "Quel'dorei", value: 'quel-dorei' },
  { name: 'Ragnaros', value: 'ragnaros' },
  { name: 'Ravencrest', value: 'ravencrest' },
  { name: 'Ravenholdt', value: 'ravenholdt' },
  { name: 'Rexxar', value: 'rexxar' },
  { name: 'Rivendare', value: 'rivendare' },
  { name: 'Runetotem', value: 'runetotem' },
  { name: 'Sargeras', value: 'sargeras' },
  { name: 'Saurfang', value: 'saurfang' },
  { name: 'Scarlet Crusade', value: 'scarlet-crusade' },
  { name: 'Scilla', value: 'scilla' },
  { name: "Sen'jin", value: 'sen-jin' },
  { name: 'Sentinels', value: 'sentinels' },
  { name: 'Shadow Council', value: 'shadow-council' },
  { name: 'Shadowmoon', value: 'shadowmoon' },
  { name: 'Shadowsong', value: 'shadowsong' },
  { name: 'Shandris', value: 'shandris' },
  { name: 'Shattered Halls', value: 'shattered-halls' },
  { name: 'Shattered Hand', value: 'shattered-hand' },
  { name: "Shu'halo", value: 'shu-halo' },
  { name: 'Silver Hand', value: 'silver-hand' },
  { name: 'Silvermoon', value: 'silvermoon' },
  { name: 'Sisters of Elune', value: 'sisters-of-elune' },
  { name: 'Skullcrusher', value: 'skullcrusher' },
  { name: 'Skywall', value: 'skywall' },
  { name: 'Smolderthorn', value: 'smolderthorn' },
  { name: 'Spinebreaker', value: 'spinebreaker' },
  { name: 'Spirestone', value: 'spirestone' },
  { name: 'Staghelm', value: 'staghelm' },
  { name: 'Steamwheedle Cartel', value: 'steamwheedle-cartel' },
  { name: 'Stonemaul', value: 'stonemaul' },
  { name: 'Stormrage', value: 'stormrage' },
  { name: 'Stormreaver', value: 'stormreaver' },
  { name: 'Stormscale', value: 'stormscale' },
  { name: 'Suramar', value: 'suramar' },
  { name: 'Tanaris', value: 'tanaris' },
  { name: 'Terenas', value: 'terenas' },
  { name: 'Terokkar', value: 'terokkar' },
  { name: 'Thaurissan', value: 'thaurissan' },
  { name: 'The Forgotten Coast', value: 'the-forgotten-coast' },
  { name: 'The Scryers', value: 'the-scryers' },
  { name: 'The Underbog', value: 'the-underbog' },
  { name: 'The Venture Co', value: 'the-venture-co' },
  { name: 'Thorium Brotherhood', value: 'thorium-brotherhood' },
  { name: 'Thrall', value: 'thrall' },
  { name: 'Thunderhorn', value: 'thunderhorn' },
  { name: 'Thunderlord', value: 'thunderlord' },
  { name: 'Tichondrius', value: 'tichondrius' },
  { name: 'Tol Barad', value: 'tol-barad' },
  { name: 'Tortheldrin', value: 'tortheldrin' },
  { name: 'Trollbane', value: 'trollbane' },
  { name: 'Turalyon', value: 'turalyon' },
  { name: 'Twisting Nether', value: 'twisting-nether' },
  { name: 'Uldaman', value: 'uldaman' },
  { name: 'Uldum', value: 'uldum' },
  { name: 'Undermine', value: 'undermine' },
  { name: 'Ursin', value: 'ursin' },
  { name: 'Uther', value: 'uther' },
  { name: 'Vashj', value: 'vashj' },
  { name: "Vek'nilash", value: 'vek-nilash' },
  { name: 'Velen', value: 'velen' },
  { name: 'Warsong', value: 'warsong' },
  { name: 'Whisperwind', value: 'whisperwind' },
  { name: 'Wildhammer', value: 'wildhammer' },
  { name: 'Windrunner', value: 'windrunner' },
  { name: 'Winterhoof', value: 'winterhoof' },
  { name: 'Wyrmrest Accord', value: 'wyrmrest-accord' },
  { name: 'Ysera', value: 'ysera' },
  { name: 'Ysondre', value: 'ysondre' },
  { name: 'Zangarmarsh', value: 'zangarmarsh' },
  { name: "Zul'jin", value: 'zul-jin' },
  { name: 'Zuluhed', value: 'zuluhed' }
]
